version: "3"
    
services:
  app:
    depends_on:
      - mysqldb
    platform: linux/x86_64
    image: 'jiobit-assessment.jar'
    ports:
      - "8081:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysqldb:3306/geo_location
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=An0thrS3crt
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_DATASOURCE_DRIVER-CLASS-NAME=com.mysql.cj.jdbc.Driver

  mysqldb:
    platform: linux/x86_64
    image: mysql:8
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    expose:
      - 3306
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=S3cret
      - MYSQL_DATABASE=geo_location
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=An0thrS3crt

volumes:
  db_data:
